on: 
 # Triggers the workflow on push or pull request events but only for the main branch
 push:
  branches: [ uat ]
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:      
      # Checkout the source code       
       - name: 'Git Checkout'  
         uses: actions/checkout@v2
         with:
          ref: uat
          fetch-depth: 0     
       - name: 'branch'
         run: git branch
       - name: 'job status'
         run: echo hello world !!!
       - name: Send Email Action (Node)
         uses: wadeww/send-email-action@v1 
         with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: kirtansahu.87@gmail.com, mbr.kirtan@gmail.com
          from: me
